### ISSUE TITLE
Include patches

### ISSUE THREAD

**Issue by jau88** [MCApollo/Archive#1]
Would be great to see the commits/patches made to allow community contributions and others to compile (perhaps upstream one day?)

**Comment by MCApollo** [comment]
Edits for the most notable packages/programs have been divided into separate repositories and are public. Any old edits here are on a backup, but I feel it's necessary to revisit them before posting them publicly due to how unclean some edits/solutions for some compiles are (like editing Makefiles by hand and other dirty tricks). 

I'm open to idea of public patches for others, but it takes time to track edits and create diff/patches out of them.
